#!/usr/bin/env bash

export SERVER_DELAY=80
export SERVER_JITTER=0
export SERVER_LOSS_START=0.0
export SERVER_LOSS_STOP=1.0
export CLIENT_DELAY_MS=80
export CLIENT_JITTER_MS=0
export CLIENT_LOSS_START=0.0
export CLIENT_LOSS_STOP=1.0

"$@"
